version: "3"

services:
  mysqldb:
    image: mysql
    container_name: mysqlnabil
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=tpachato
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: nabil007/spring
    restart: on-failure
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angular:
    image: nabil007/crud-front-tuto
    container_name: crud-front-tuto
    ports:
      - 4200:80
volumes:
  db:
  
