version: "3"

services: 
  app: 
    build: "."
    depends_on: 
      - mysqldb
    ports: 
      - "9092:9092"
    restart: on-failure
    stdin_open: true
    tty: true
    
  mysqldb: 
    environment: 
      MYSQL_ROOT_PASSWORD: root
    image: "mysql:8"
    ports: 
      - "9096:9096"
    restart: unless-stopped
    volumes: 