version: "3"

services: 
  app: 
    build: "."
    depends_on: 
      - mysqldb
    ports: 
      - "8089:8089"
    restart: on-failure
    stdin_open: true
    tty: true
    
  mysqldb: 
    environment: 
      MYSQL_ROOT_PASSWORD: root
    image: "mysql:8"
    ports: 
      - "3333:3333"
    restart: unless-stopped
    volumes: 
      - "/home/mysql/data:/var/lib/mysql"
  angular:
    image: ahmedbndhm/docker-angular
    container_name: docker-angular
    ports:
      - 4200:80
