version: "3"

services: 
  app: 
    build: "."
    depends_on: 
      - mysqldb
    ports: 
      - "9092:9092"
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: 
      - .m2/root/.m2
  mysqldb: 
    environment: 
      MYSQL_ROOT_PASSWORD: root
    image: "mysql:8"
    ports: 
      - "9092:9092"
    restart: unless-stopped
    volumes: 
      - "/home/mysql/data:/var/lib/mysql"

