version: "3"

services: 
  app: 
    build: "."
    depends_on: 
      - mysqldb
    ports: 
      - "8089:8089"
    restart: on-failure
    stdin_open: true
    tty: true
    
  mysqldb: 
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=tpachat
    image: "mysql:8"
    ports: 
      - "3310:3306"
    restart: unless-stopped
    volumes: 
      - "/var/lib/mysql"
  angular:
    image: seifeddineelbehi/docker-angular
    container_name: docker-angular
    ports:
      - 4200:80