  version "1.0"
  
  service:
    mysqldb:
      image: mysql:8
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "9092:9092"
      volumes:
        - /home/mysql/data:/var/lib/mysql
    app:
      depends_on:
        - mysqldb
      build: .
      restart : on-failure
      ports:
        - "9092:9092"
      volumes:
        - .m2/root/.m2
      stdin_open: true
      tty: true
        
       